### ISSUE TITLE
Does the Go SDK have echo cancellation

### ISSUE THREAD

**Issue by LLLLimbo** [livekit/server-sdk-go#154]
I noticed that other clients have the `echoCancellation` option, but I didn't find it in Go's client

**Comment by cnderrauber** [comment]
The go sdk doesn't contain capture module, audio process module, encoder like other clients so it won't have `echoCancellation`. Since it only include the packetization and the webrtc transport, so if you want to use go sdk with a microphone, you should have capture/APM/encoder module work together with the sdk, then those modules are responsible for the `echoCancellation`

**Comment by LLLLimbo** [comment]
> 

Thank you for your answer, can you provide more advice and guidance on this?
