### ISSUE TITLE
How to synchronize audio and video when using NewLocalReaderTrack for publishing.

### ISSUE THREAD

**Issue by ocean2811** [livekit/server-sdk-go#212]
I executed the following command to separate audio and video files from an MP4 file, and then published them using NewLocalReaderTrack. However, the audio and video were not synchronized for the viewer. I tried modifying the `server-sdk-go` code to set the same streamID for both tracks, but it still did not work.

`
ffmpeg -i <input.mp4> \
  -c:v libx264 -bsf:v h264_mp4toannexb -b:v 2M -profile baseline -pix_fmt yuv420p \
    -x264-params keyint=120 -max_delay 0 -bf 0 <output.h264> \
  -c:a libopus -page_duration 20000 -vn <output.ogg>
`

**Comment by davidzhao** [comment]
Synchronization here is tricky. You'd need to set the sample duration of video frames correctly (matching FPS and source timestamps) in order to ensure it plays back at the same time.

The presentation timestamp is calculated from the Duration value of the Samples that you are producing. The SDK provides a convenience function of computing it for you given the framerate.

**Comment by BucherLi** [comment]
> ky. You'd need to set the sample duration of video frames correctly

can you give a example please?
