### ISSUE TITLE
WASM support

### ISSUE THREAD

**Issue by tmc** [livekit/server-sdk-go#39]
Are you expecting/planning on including a WASM target in this codebase?

**Comment by davidzhao** [comment]
hey @tmc, WASM support isn't in our roadmap at the moment. The reason is there's quite a bit of limitations of WASM when it comes to networking. In the browser we don't have direct control of the networking layer so most of the webrtc stack in the Go SDK would not be applicable.

There is a way to map WebRTC APIs to `RTCPeerConnection` that browsers expose, but there will be quite a bit that will be lost in translation.

If you look at our JS client SDK, there are also a (small) bit of code that deals with browser-specific compatibility issues.
